# Generated by Django 5.2 on 2025-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('name', models.CharField(editable=False, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, unique=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('citizenship_number', models.CharField(max_length=20, unique=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
