# Generated by Django 5.1.3 on 2025-06-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_id']},
        ),
    ]
