# Generated by Django 5.2 on 2025-06-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('saving_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('loan_repayment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque')], default='cash', max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customer.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
