# Generated by Django 5.2 on 2025-06-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
