# Generated by Django 5.2 on 2025-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
