# Generated by Django 5.2 on 2025-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
