# Generated by Django 5.2 on 2025-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_transaction_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
