# Generated by Django 5.2 on 2025-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_transaction_other_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('interest', 'Interest'), ('cheque', 'Cheque')], default='cash', max_length=50),
        ),
    ]
