# Generated by Django 5.2 on 2025-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
