# Generated by Django 5.2 on 2025-06-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='customer.member')),
            ],
        ),
        migrations.CreateModel(
            name='YearlyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Fiscal year starting in Shrawan')),
                ('interest_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_interests', to='customer.member')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('customer', 'year')},
            },
        ),
    ]
