# Generated by Django 5.1.3 on 2025-06-08 08:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_member_options'),
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_refunded', models.DecimalField(decimal_places=2, help_text='Amount withdrawn/refunded from savings', max_digits=12)),
                ('refund_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_refunds', to='customer.member')),
            ],
        ),
    ]
