# Generated by Django 5.1.3 on 2025-06-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0002_savingrefund'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='savingrefund',
            options={'ordering': ['refund_date']},
        ),
    ]
