# Generated by Django 5.2 on 2025-06-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0003_alter_deposit_options_alter_savingrefund_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='deposit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingrefund',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=50),
        ),
    ]
