# Generated by Django 5.2 on 2025-06-08 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0004_deposit_method_deposit_remarks_savingrefund_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='savingrefund',
            old_name='method',
            new_name='payment_method',
        ),
    ]
