# Generated by Django 5.2 on 2025-06-08 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0005_rename_method_deposit_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearlyinterest',
            old_name='interest_received',
            new_name='current_interest_rate',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='yearlyinterest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yearlyinterest',
            name='previous_interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
