# Generated by Django 5.2 on 2025-06-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0006_rename_interest_received_yearlyinterest_current_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyinterest',
            name='current_interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='yearlyinterest',
            name='previous_interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
