# Generated by Django 5.2 on 2025-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0007_alter_yearlyinterest_current_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlyinterest',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='yearlyinterest',
            name='current_interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest calculated for current fiscal year', max_digits=12),
        ),
        migrations.AddField(
            model_name='yearlyinterest',
            name='previous_interest_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest calculated for previous fiscal year', max_digits=12),
        ),
    ]
