# Generated by Django 5.2 on 2025-06-16 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_transaction_other_fee'),
        ('saving', '0009_alter_yearlyinterest_current_interest_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_fee', to='customer.member')),
            ],
        ),
    ]
