# Generated by Django 5.2 on 2025-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0010_otherfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherfee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlyinterest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
