# Generated by Django 5.2 on 2025-07-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0011_otherfee_remarks_yearlyinterest_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingrefund',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('interest', 'Interest')], default='cash', max_length=50),
        ),
    ]
