# Generated by Django 5.2 on 2025-07-01 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('stationary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('freight', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_saving', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('printing', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('photocopy', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('miscellaneous', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TotalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Nepali Fiscal Year starting in Shrawan', unique=True)),
                ('total_stationary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_interest_saving', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_printing', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_photocopy', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_fuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_miscellaneous', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
