# Generated by Django 5.2 on 2025-07-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalexpense',
            options={'ordering': ['-fiscal_year']},
        ),
        migrations.RemoveField(
            model_name='totalexpense',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='totalexpense',
            name='total_expense',
        ),
        migrations.RemoveField(
            model_name='totalexpense',
            name='year',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='totalexpense',
            name='fiscal_year',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalexpense',
            name='total_overall',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='totalexpense',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
