# Generated by Django 5.2 on 2025-07-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_totalexpense_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='interest_saving',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='miscellaneous',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='photocopy',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='printing',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='stationary',
        ),
        migrations.RemoveField(
            model_name='totalexpense',
            name='total_miscellaneous',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('stationary', 'Stationary'), ('rent', 'Rent'), ('freight', 'Freight'), ('bonus', 'Bonus'), ('interest_saving', 'Interest on Saving'), ('printing', 'Printing'), ('photocopy', 'Photocopy'), ('fuel', 'Fuel'), ('misc', 'Miscellaneous')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalexpense',
            name='total_misc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
