# Generated by Django 5.2 on 2025-07-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_bonus_remove_expense_freight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalexpense',
            old_name='total_misc',
            new_name='total_miscellaneous',
        ),
    ]
