# Generated by Django 5.2 on 2025-07-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_total_misc_totalexpense_total_miscellaneous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('stationary', 'Stationary'), ('rent', 'Rent'), ('freight', 'Freight'), ('bonus', 'Bonus'), ('interest_saving', 'Interest on Saving'), ('printing', 'Printing'), ('photocopy', 'Photocopy'), ('fuel', 'Fuel'), ('miscellaneous', 'Miscellaneous')], max_length=30),
        ),
    ]
