# Generated by Django 5.2 on 2025-06-06 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Original loan principal', max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual interest rate (e.g. 0.075 for 7.5%)', max_digits=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('remaining_principal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer.member')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=15)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loan.loan')),
            ],
            options={
                'ordering': ['repayment_date'],
            },
        ),
    ]
