# Generated by Django 5.2 on 2025-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_renewed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
