# Generated by Django 5.2 on 2025-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Annual interest rate (e.g. 0.075 for 7.5%)', max_digits=5),
        ),
    ]
