# Generated by Django 5.2 on 2025-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_loan_remarks_repayment_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='remaining_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
