# Generated by Django 5.2 on 2025-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_repayment_remaining_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='previous_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
