# Generated by Django 5.2 on 2025-06-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_repayment_previous_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-repayment_date']},
        ),
    ]
