# Generated by Django 5.2 on 2025-06-06 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_purchased', models.PositiveIntegerField(help_text='Number of shares bought')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per share at purchase time', max_digits=10)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_purchases', to='customer.member')),
            ],
        ),
        migrations.CreateModel(
            name='ShareRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_refunded', models.PositiveIntegerField(help_text='Number of shares refunded/withdrawn')),
                ('refund_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_refunds', to='customer.member')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('dividend_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('distribution_date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='customer.member')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('customer', 'year')},
            },
        ),
    ]
