# Generated by Django 5.2 on 2025-06-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dividend',
        ),
    ]
