# Generated by Django 5.2 on 2025-06-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_delete_dividend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharecapital',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='sharecapital',
            name='units_purchased',
        ),
        migrations.RemoveField(
            model_name='sharerefund',
            name='refund_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='sharerefund',
            name='units_refunded',
        ),
        migrations.AddField(
            model_name='sharecapital',
            name='share_amount',
            field=models.IntegerField(default=1, help_text='Share Amount at purchase time', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharerefund',
            name='refund_amount',
            field=models.IntegerField(default=1, help_text='Amount refunded for shares', max_length=10),
            preserve_default=False,
        ),
    ]
