# Generated by Django 5.2 on 2025-06-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_remove_sharecapital_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharecapital',
            name='share_amount',
            field=models.IntegerField(help_text='Share Amount at purchase time'),
        ),
        migrations.AlterField(
            model_name='sharerefund',
            name='refund_amount',
            field=models.IntegerField(help_text='Amount refunded for shares'),
        ),
    ]
