# Generated by Django 5.2 on 2025-06-15 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_member_options'),
        ('share', '0004_alter_sharecapital_share_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Current share balance after refunds or purchase')),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_balances', to='customer.member')),
            ],
        ),
    ]
