# Generated by Django 5.2 on 2025-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_sharebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharebalance',
            name='balance',
            field=models.IntegerField(default=0, help_text='Current share balance after refunds or purchases'),
        ),
    ]
